### ISSUE TITLE
What should I buy to program the JTAG port on this computer?

### ISSUE THREAD

**Issue by igobysoandso** [machdyne/konfekt#1]
If there exists a difference, which cable and programmer out of the couple that openFPGALoader supports is the fastest for this computer?

**Comment by machdyne** [comment]
Hello. I haven't tested speeds of various programmers but programming the FPGA SRAM over JTAG is generally very fast. Programing the flash over JTAG is about the same speed as with the USB DFU programmer that ships with Konfekt.

Any JTAG programmer should work. I have used a ~10 EUR "USB Blaster" clone from Amazon. You can also use a Raspberry Pi Pico or [Werkzeug](github.com/machdyne/werkzeug) with the [pico-dirtyJtag](https://github.com/phdussud/pico-dirtyJtag) firmware.

Those options are all supported by openFPGALoader.

**Comment by igobysoandso** [comment]
This blog post from a couple months ago recommends digging deep into the firmware for a couple of knockoff USB Blasters, or buying the official one for $300, but the pinout of the official one doesn't match this README's pinout. (Blog post: https://www.downtowndougbrown.com/2024/06/fixing-a-knockoff-altera-usb-blaster-that-never-worked/)

Pin 1: TCK, Pin 2: GND, Pin 3: TDO, Pin 4: VCC, Pin 5: TMS, Pins 6-8: Unused, Pin 9: TDI, Pin 10: GND

README: Pin 1: TCK, Pin 2: TDI, Pin 3: TDO, Pin 4: TMS, Pin 5: 5V0, Pin 6: GND

(Official USB Blaster JTAG pinout: https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6133/Intel®_FPGA_Download_Cable_User_Guide_V2024.01.16.pdf)

**Comment by machdyne** [comment]
For the actual cable I'm using individual Dupont jumper wires.

If you have a 6-pin ribbon cable with 2x3 female 2.54mm headers you can connect the jumper wires from the programmer to one end of the cable, and the other end to the board. That way you can more easily unplug/plug the cable into the board.

I will look into the possibility of offering some adapter cables in the future.
